[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Form handling
[[forms]]
  name = "newsletter"

[[forms]]
  name = "contact"

# Redirects for form submissions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://pagead2.googlesyndication.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self' https://www.google-analytics.com;"

# Form submission success pages
[[redirects]]
  from = "/newsletter"
  to = "/newsletter.html?subscribed=true"
  status = 301
  force = false

[[redirects]]
  from = "/contact"
  to = "/thank-you.html"
  status = 301
  force = false

# SEO and performance optimizations
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Preconnect to external domains for performance
[[headers]]
  for = "/index.html"
  [headers.values]
    Link = "</css/style.css>; rel=preload; as=style, <https://cdnjs.cloudflare.com>; rel=preconnect; crossorigin, <https://www.googletagmanager.com>; rel=preconnect"